### ISSUE TITLE
Initialise handler from yaml file (logging integration, dictConfig)

### ISSUE THREAD

**Issue by JPFrancoia** [getsentry/sentry-python#1216]
Hello,

I would like to create a Sentry handler for my project. I am aware that the recommended way is to use the snippet described here: https://docs.sentry.io/platforms/python/guides/logging/:

```python
import logging
import sentry_sdk
from sentry_sdk.integrations.logging import LoggingIntegration

# All of this is already happening by default!
sentry_logging = LoggingIntegration(
    level=logging.INFO,        # Capture info and above as breadcrumbs
    event_level=logging.ERROR  # Send errors as events
)
sentry_sdk.init(
    dsn="

https://examplePublicKey@o0.ingest.sentry.io/0",
    integrations=[sentry_logging]
)
```

However, this implies writing some actual code to get the Sentry logger working. The config is also done within the code, which isn't optimal. I quite like using a yaml file to configure mutliple loggers/handlers. This clearly separates the code from the config, and it's very powerful: I can log to the console + a local file + clouwatch + sentry, etc, without ever touching the code.

I have tried this:

```yaml
---
version: 1
disable_existing_loggers: false

formatters:
    default:
        format: "%(asctime)s - %(levelname)8s %(message)-50s [%(filename)s, l %(lineno)d in %(funcName)s]"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: default

    root_file_handler:
        class: logging.FileHandler
        level: DEBUG
        filename: export.log
        formatter: default

    #sentry_handler:
        #class: sentry_sdk.integrations.logging.LoggingIntegration
        #level: ERROR
        ##dsn: http://*****:*****@sentry.*****.local/11
        #formatter: default

    #sentry_event:
        #class: sentry_sdk.integrations.logging.SentryHandler
        #level: ERROR
        ##dsn: http://*****:*****@sentry.*****.local/11
        #formatter: default

    #sentry_breadcrumbs:
        #class: sentry_sdk.integrations.logging.BreadcrumbHandler
        #level: INFO
        ##dsn: http://*****:*****@sentry.*****.local/11
        #formatter: default
        
    #sentry_event:
        #class: sentry_sdk.integrations.logging.EventHandler
        #level: ERROR
        ##dsn: http://*****:*****@sentry.*****.local/11
        #formatter: default

root:
    handlers: [console, root_file_handler, sentry_event]
```

The commented configs are my attempts at getting a Sentry handler working. Most of the time I get this error:

```
Traceback (most recent call last):
  File "/Users/jean-patrickfrancoia/.pyenv/versions/3.7.10/lib/python3.7/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/Users/jean-patrickfrancoia/.pyenv/versions/3.7.10/lib/python3.7/logging/config.py", line 736, in configure_handler
    result = factory(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'dsn'
```

which kinda makes sense. Is there a way to do achieve what I want with `sentry-python` ? It used to work with raven: https://raven.readthedocs.io/en/stable/integrations/logging.html

Thanks
