### ISSUE TITLE
Add cloud resource context

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-python#1820]
### Problem Statement

When a user gets an error or transacation (performance event) in Sentry they may not know the specific of where that particular service is hosted. Where possible it would be great to know some contextual information about where that service is hosted to speed up problem solving and eventually deploying a fix

example data
```
cloud:
  provider: aws|gcp|azure
  region: ...
  [account|project]_id: ...
  service: ec2, cloud-functions, ...
  resource: <ARN>
```

### Solution Brainstorm

Add this data using the [Contexts Interface](https://develop.sentry.dev/sdk/event-payloads/contexts/) of the event payload

- [x] Define a standard set of contextual data: 
  - example above
- [ ] determine how to fetch that data from top hosting platforms
  - [x] AWS
  - [x] GCP
  - [ ] Azure
  - [ ] Vercel
  - [ ] Netlify
  - [ ] others?
- [ ] Python SDK should check for this context and populate it in the event when possible
 - [ ] relay changes needed prior to

Future considerations:
- contexts should be searchable in product, changes will be needed in sentry backend so this data can be used to filter issues
