### ISSUE TITLE
sentry_sdk.errors DEBUG logs are emitted without debug=True

### ISSUE THREAD

**Issue by alex-700** [getsentry/sentry-python#4266]
### How do you use Sentry?

Self-hosted/on-premise

### Version

2.25.1

### Steps to Reproduce

There is simple FastAPI project.

<details><summary>pyproject.toml</summary>
<p>

```toml
[project]
name = "bug"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "pyyaml>=6.0.2",
    "sentry-sdk>=2.25.1",
    "uvicorn>=0.34.0",
]
```

</p>
</details> 

<details><summary>main.py</summary>
<p>

```python
import fastapi
import sentry_sdk

sentry_sdk.init()

app = fastapi.FastAPI()


@app.get("/")
def hello():
    print()
```

</p>
</details> 

<details><summary>log_conf.yaml</summary>
<p>

```yaml
version: 1
disable_existing_loggers: False
formatters:
  default:
    # "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    # "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  default_stdout:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
root:
  level: DEBUG
  handlers:
    - default_stdout
  propagate: no
```

</p>
</details> 

When I run it via `uvicorn`, the [`_DebugFilter`](https://github.com/getsentry/sentry-python/blob/97c435a82c4ddca2706794ed90b74f6527f8162f/sentry_sdk/debug.py#L11) seems to be not added as filter.

### Expected Result

```bash
uv run uvicorn main:app --log-config log_conf.yaml
```
no DEBUG logs from sentry_sdk, while I do not use SENTRY_DEBUG (or debug=True).

### Actual Result

```bash
uv run uvicorn main:app --log-config log_conf.yaml
```

There are a lot of DEBUG logs from sentry_sdk.
