### ISSUE TITLE
redis integration creates incomplete/empty breadcrumbs

### ISSUE THREAD

**Issue by Birne94** [getsentry/sentry-python#485]
When using the [redis integration](https://docs.sentry.io/platforms/python/redis/) (sentry-sdk 0.11.1), we are not seeing the executed query in the breadcrumbs. Instead, some of the entries are empty, some only contain the accessed key (commands executed are `SET`, `EVALSHA` and `SET` again):

<img width="803" alt="Screen Shot 2019-08-27 at 15 07 59" src="https://user-images.githubusercontent.com/617722/63773997-9f26ef00-c8dc-11e9-836b-b2c9d8608440.png">

The event data contains the following entries:

```yml
{
    "breadcrumbs": {
        "values": [
            {
                "category": "redis",
                "timestamp": 1566910541.535,
                "type": "redis",
                "data": {
                    "redis.key": "<my-key>:0dec1124-2216-42d9-9e20-f0535ed70e04"
                },
                "level": "info"
            },
            {
                "category": "redis",
                "timestamp": 1566910541.588,
                "type": "redis",
                "level": "info"
            },
            {
                "category": "redis",
                "timestamp": 1566910541.607,
                "type": "redis",
                "data": {
                    "redis.key": "<my-key>:0dec1124-2216-42d9-9e20-f0535ed70e04"
                },
                "level": "info"
            }
        ]
    }
}
```
