### ISSUE TITLE
Create a v1.0.0 and start enforcing semver

### ISSUE THREAD

**Issue by fclairamb** [getsentry/sentry-python#696]
Hi,

Thank you for your amazing work.

Can you please release a version v1.x.x? This would help people like [us](https://github.com/habx/) who are using [dependabot](https://dependabot.com/) massively and are using automatic minor version merges.

Your JS SDK is in version 5, your python SDK API has been really stable for years, so there's no reason to delay this v1.

Thank you !

**Comment by untitaker** [comment]
Hi @fclairamb ,

Before we release 1.0 we want to do a major sweep over the entire public API surface to fix some long-standing API flaws that we've been punting on. No huge breakage, but still some breakage as prohibited by semver. We currently don't have the time for that, so by that logic we cannot just release 1.0 right now.

As per the `CHANGELOG.md` we provide semver guarantees like it is the case in npm: A PATCH-version release is semantically equivalent to a minor version release post-1.0. That means every `0.x` release can contain breaking changes but a `0.1.x` release never will. I'm not sure why this would be causing issues with dependabot... we're using dependabot ourselves to bump dependencies in some of our repos.

Let me know if you have further questions.

**Comment by untitaker** [comment]
Closing due to lack of activity. 1.0 will definetly be released eventually :)

**Comment by fclairamb** [comment]
I'm speaking about the "automerge" feature of dependabot. We're using it massively and it doesn't have any "semver:minor" for "pre-1.0.0" releases rule available.

I'm probably not going to change your opinion on that because, even if everybody agrees on the scope of semver, reaching an agreement on what constitutes a v1 is harder. Still... I'm going to say it: Releasing to v1 now and improving your API in a v2 doesn't seem to have any negative effect on anyone. Because you have so many people who did install this version in their production environment and you are responsible people, you are in effect providing a v1.

FYI, on most of our python repositories it looks like this:
```yaml
version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "auto"
    # https://dependabot.com/docs/config-file/#automerged_updates
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
      - match:
          dependency_type: "all"
          update_type: "in_range"
```
